# ################################
# Model: VGG2 + LiGRU with time pooling for efficiency
# Additions: TimeDomainSpecAugment
# Authors: Mirco Ravanelli & Peter Plantinga 2020
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1236
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/verifier/<seed>
cer_file: !ref <output_folder>/cer.txt
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

# Data files
data_folder: !PLACEHOLDER
csv_train: !ref <data_folder>/train.csv
csv_valid: !ref <data_folder>/dev.csv
csv_test: !ref <data_folder>/test.csv
# print_id: ksd062p0

# Training parameters
number_of_epochs: 50
batch_size: 8
lr: 1.0
device: 'cuda:0'
ctc_weight: 1.0
align_weight: 0.0
verify_weight: 1.0

# Feature parameters
sample_rate: 16000
n_fft: 400
n_mels: 40

# recognizer model parameters
activation: !name:torch.nn.LeakyReLU
dropout: 0.15
cnn_blocks: 2
cnn_channels: (128, 256)
cnn_kernelsize: (3, 3)
rnn_layers: 4
rnn_neurons: 512
rnn_bidirectional: True
dnn_blocks: 2
dnn_neurons: 512
output_neurons: 39
blank_index: !ref <output_neurons> - 1

# verifier model parameters
verifier_emb_size: 32
verifier_rnn_size: 256
verifier_rnn_layers: 2
verifier_char_rnn_size: 256
verifier_char_rnn_layers: 2
verifier_dnn_size: 256
verifier_dnn_layers: 2
verifier_dropout: 0.1

epoch_counter: !new:speechbrain.EpochCounter
    limit: !ref <number_of_epochs>

train_loader: !new:speechbrain.data_io.DataLoaderFactory
    csv_file: !ref <csv_train>
    batch_size: !ref <batch_size>
    sentence_sorting: ascending
    output_folder: !ref <output_folder>
    csv_read: [wav, char, verify]
    avoid_if_longer_than: 7.5

valid_loader: !new:speechbrain.data_io.DataLoaderFactory
    csv_file: !ref <csv_valid>
    batch_size: !ref <batch_size>
    sentence_sorting: ascending
    output_folder: !ref <output_folder>
    csv_read: [wav, char, verify]

test_loader: !new:speechbrain.data_io.DataLoaderFactory
    csv_file: !ref <csv_test>
    batch_size: !ref <batch_size>
    sentence_sorting: ascending
    output_folder: !ref <output_folder>
    csv_read: [wav, char, verify]

normalize: !new:speechbrain.processing.InputNormalization

augmentation: !new:speechbrain.lobes.TimeDomainSpecAugment
    sample_rate: !ref <sample_rate>
    speeds: [95, 100, 105]

compute_features: !new:speechbrain.lobes.Fbank
    sample_rate: !ref <sample_rate>
    n_fft: !ref <n_fft>
    n_mels: !ref <n_mels>

recognizer: !new:speechbrain.lobes.CRDNN
    input_shape: [null, null, !ref <n_mels>]
    activation: !ref <activation>
    dropout: !ref <dropout>
    cnn_blocks: !ref <cnn_blocks>
    cnn_channels: !ref <cnn_channels>
    cnn_kernelsize: !ref <cnn_kernelsize>
    time_pooling: False
    using_2d_pooling: True
    rnn_class: !name:speechbrain.nnet.LSTM
    rnn_layers: !ref <rnn_layers>
    rnn_neurons: !ref <rnn_neurons>
    rnn_bidirectional: !ref <rnn_bidirectional>
    dnn_blocks: !ref <dnn_blocks>
    dnn_neurons: !ref <dnn_neurons>

recognizer_output: !new:speechbrain.nnet.Linear
    input_size: !ref <dnn_neurons>
    n_neurons: !ref <output_neurons>
    bias: True

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

ctc_loss: !name:speechbrain.nnet.ctc_loss
    blank_index: !ref <blank_index>

verifier: !new:verifier.Verifier
    input_size: !ref <dnn_neurons>
    vocab_size: !ref <output_neurons>
    emb_size: !ref <verifier_emb_size>
    rnn_size: !ref <verifier_rnn_size>
    rnn_layers: !ref <verifier_rnn_layers>
    rnn_dropout: !ref <verifier_dropout>
    char_rnn_size: !ref <verifier_char_rnn_size>
    char_rnn_layers: !ref <verifier_char_rnn_layers>
    char_rnn_dropout: !ref <verifier_dropout>
    dnn_size: !ref <verifier_dnn_size>
    dnn_layers: !ref <verifier_dnn_layers>
    dnn_dropout: !ref <verifier_dropout>

bce_loss: !name:speechbrain.nnet.BCE_loss

modules:
    recognizer: !ref <recognizer>
    recognizer_output: !ref <recognizer_output>
    verifier: !ref <verifier>
    normalize: !ref <normalize>

opt_class: !name:torch.optim.Adadelta
    lr: !ref <lr>
    rho: 0.95
    eps: 1.e-8

lr_annealing: !new:speechbrain.nnet.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: 0.0025
    annealing_factor: 0.8
    patient: 0

checkpointer: !new:speechbrain.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        recognizer: !ref <recognizer>
        recognizer_output: !ref <recognizer_output>
        verifier: !ref <verifier>
        scheduler: !ref <lr_annealing>
        normalizer: !ref <normalize>
        counter: !ref <epoch_counter>

train_logger: !new:speechbrain.FileTrainLogger
    save_file: !ref <train_log>

cer_computer: !name:speechbrain.ErrorRateStats
verify_computer: !name:speechbrain.BinaryMetricStats
